[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = ['Shougo/vimproc.vim', 'thinca/vim-quickrun', 'osyo-manga/shabadou.vim']
hook_add = '''
  " 書き込み後にシンタックスチェックを行う
  let g:watchdogs_check_BufWritePost_enable = 1
  " 閉じるときにはチェックしない
  let g:watchdogs_check_BufWritePost_enable_on_wq = 0
  " 各種設定
  let g:quickrun_config = {
  \   '_' : {
  \     "runner" : "vimproc",
  \     "runner/vimproc/updatetime" : 10,
  \   },
  \   'watchdogs_checker/_' : {
  \     'outputter/quickfix/open_cmd' : '',
  \   }
  \ }
  " watchdogs.vim の設定を追加
  call watchdogs#setup(g:quickrun_config)
'''

[[plugins]]
repo = 'pocke/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'KazuakiM/vim-qfsigns'
