[[plugins]]
# プラグイン管理
repo = 'Shougo/dein.vim'

[[plugins]]
# カーソル位置のコンテキストのfile typeを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]]
# カーソル位置のコンテキストに合わせてfile typeを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
# toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
# 貼り付け時に自動でペーストモードにする
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
# カッコを自動で閉じる
repo = 'cohama/lexima.vim'

[[plugins]]
# 統合インターフェース(nvim用)
repo = 'Shougo/denite.nvim'
if = "has('nvim')"

[[plugins]]
# 補完(nvim用)
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
# カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]]
# Pythonの補完
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
# Pythonのインデントを良い感じにする
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
